const { Router } = require('express')
const authRoutes = require('./auth.routes')
const labRoutes = require('./labs.routes')
const categoryRoutes = require('./categories.routes')
const inventoryRoutes = require('./inventory.routes')
const borrowingRoutes = require('./borrowings.routes')
const dashboardRoutes = require('./dashboard.routes')
const exportRoutes = require('./export.routes')
const auditRoutes = require('./audit.routes')
const userRoutes = require('./users.routes')
const notificationRoutes = require('./notifications.routes')
const importRoutes = require('./import.routes')
const router = Router()

router.use('/auth', authRoutes)
router.use('/labs', labRoutes)
router.use('/categories', categoryRoutes)
router.use('/inventory', inventoryRoutes)
router.use('/borrowings', borrowingRoutes)
router.use('/dashboard', dashboardRoutes)
router.use('/export', exportRoutes)
router.use('/audit', auditRoutes)
router.use('/users', userRoutes)
router.use('/notifications', notificationRoutes)
router.use('/import', importRoutes)

module.exports = router
